/// When a command can act on several kinds of objects with only one
/// parse structure required, use these constants to designate the
/// object type.  Note that commands typically don't support all the types.
pub enum ObjectKind {
    AccessMethod,
    Aggregate,
    Amop,
    Amproc,
    Attribute,
    Cast,
    Collation,
    Column,
    Conversion,
    Database,
    Defacl,
    Default,
    Domain,
    Domconstraint,
    EventTrigger,
    Extension,
    Fdw,
    ForeignServer,
    ForeignTable,
    Function,
    Index,
    Language,
    Largeobject,
    MaterialView,
    Operator,
    OperatorClass,
    OperatorFamily,
    Policy,
    Procedure,
    Publication,
    PublicationRel,
    Role,
    Routine,
    Rule,
    Schema,
    Sequence,
    StatisticExt,
    Statistics,
    Subscription,
    TableConstraint,
    Table,
    Tablespace,
    TextSearchDictionary,
    TextSearchParser,
    TextSearchTemplate,
    TextSerachConfiguration,
    Transform,
    Trigger,
    Type,
    UserMapping,
    View,
}

